export const FETCH_CART = "FETCH_CART";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";

export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";

export const FIND_CART = "FIND_CART";
export const FIND_CART_SUCCESS = "FIND_CART_SUCCESS";

export const REMOVE_CARTS = "REMOVE_CARTS";
export const REMOVE_CARTS_SUCCESS = "REMOVE_CARTS_SUCCESS";
