export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";

export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";

export const EXPORT_ORDER = "EXPORT_ORDER";
export const EXPORT_ORDER_SUCCESS = "EXPORT_ORDER_SUCCESS";
