export const FETCH_PRODUCT_TYPE = "FETCH_PRODUCT_TYPE";
export const FETCH_PRODUCT_TYPE_SUCCESS = "FETCH_PRODUCT_TYPE_SUCCESS";

export const FETCH_PRODUCT_TYPE_BY_RATING = "FETCH_PRODUCT_TYPE_BY_RATING";
export const FETCH_PRODUCT_TYPE_BY_RATING_SUCCESS = "FETCH_PRODUCT_TYPE_BY_RATING_SUCCESS";

export const FIND_PRODUCT_TYPE = "FIND_PRODUCT_TYPE";
export const FIND_PRODUCT_TYPE_SUCCESS = "FIND_PRODUCT_TYPE_SUCCESS";

export const OPEN_FORM = "OPEN_FORM";
export const ADD_PRODUCT_TYPE = "ADD_PRODUCT_TYPE";
export const ADD_PRODUCT_TYPE_SUCCESS = "ADD_PRODUCT_TYPE_SUCCESS";

export const SET_PRODUCT_TYPE_EDITING = "SET_PRODUCT_TYPE_EDITING";

export const UPDATE_PRODUCT_TYPE = "UPDATE_PRODUCT_TYPE";
export const UPDATE_PRODUCT_TYPE_SUCCESS = "UPDATE_PRODUCT_TYPE_SUCCESS";

export const DELETE_PRODUCT_TYPE = "DELETE_PRODUCT_TYPE";
export const DELETE_PRODUCT_TYPE_SUCCESS = "DELETE_PRODUCT_TYPE_SUCCESS";

export const RATING_PRODUCT_TYPE = "RATING_PRODUCT_TYPE";
export const RATING_PRODUCT_TYPE_SUCCESS = "RATING_PRODUCT_TYPE_SUCCESS";
