export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";

export const OPEN_FORM = "OPEN_FORM";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";

export const SET_PRODUCT_EDITING = "SET_PRODUCT_EDITING";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const LIST_CHOOSE = "LIST_CHOOSE";
export const CHOOSE_PRODUCT = "CHOOSE_PRODUCT";
export const CANCEL_PRODUCT = "CANCEL_PRODUCT";
export const UP_PRODUCT = "UP_PRODUCT";
export const DOWN_PRODUCT = "DOWN_PRODUCT";
export const STEP_PRODUCT = "STEP_PRODUCT";

export const SELL = "SELL";
export const SELL_SUCCESS = "SELL_SUCCESS";

export const BUY = "BUY";
export const BUY_SUCCESS = "BUY_SUCCESS";

export const FETCH_PRODUCT_SOLD_OUT = "FETCH_PRODUCT_SOLD_OUT";
export const FETCH_PRODUCT_SOLD_OUT_SUCCESS = "FETCH_PRODUCT_SOLD_OUT_SUCCESS";
/////////////////////////////////////////////////
export const FETCH_PRODUCT_BY_TYPE = "FETCH_PRODUCT_BY_TYPE";
export const FETCH_PRODUCT_BY_TYPE_SUCCESS = "FETCH_PRODUCT_BY_TYPE_SUCCESS";

export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";

export const CUSTOMER_BUY = "CUSTOMER_BUY";
export const CUSTOMER_BUY_SUCCESS = "CUSTOMER_BUY_SUCCESS";
