export const FETCH_PRODUCT_TYPE = "FETCH_PRODUCT_TYPE";
export const FETCH_PRODUCT_TYPE_SUCCESS = "FETCH_PRODUCT_TYPE_SUCCESS";
export const FETCH_PRODUCT_TYPE_FAILED = "FETCH_PRODUCT_TYPE_FAILED";

export const OPEN_FORM = "OPEN_FORM";
export const ADD_PRODUCT_TYPE = "ADD_PRODUCT_TYPE";
export const ADD_PRODUCT_TYPE_SUCCESS = "ADD_PRODUCT_TYPE_SUCCESS";
export const ADD_PRODUCT_TYPE_FAILED = "ADD_PRODUCT_TYPE_FAILED";

export const SET_PRODUCT_TYPE_EDITING = "SET_PRODUCT_TYPE_EDITING";

export const UPDATE_PRODUCT_TYPE = "UPDATE_PRODUCT_TYPE";
export const UPDATE_PRODUCT_TYPE_SUCCESS = "UPDATE_PRODUCT_TYPE_SUCCESS";
export const UPDATE_PRODUCT_TYPE_FAILED = "UPDATE_PRODUCT_TYPE_FAILED";

export const DELETE_PRODUCT_TYPE = "DELETE_PRODUCT_TYPE";
export const DELETE_PRODUCT_TYPE_SUCCESS = "DELETE_PRODUCT_TYPE_SUCCESS";
export const DELETE_PRODUCT_TYPE_FAILED = "DELETE_PRODUCT_TYPE_FAILED";
