export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILED = "FETCH_PRODUCT_FAILED";

export const OPEN_FORM = "OPEN_FORM";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const SET_PRODUCT_EDITING = "SET_PRODUCT_EDITING";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const LIST_CHOOSE = "LIST_CHOOSE";
export const CHOOSE_PRODUCT = "CHOOSE_PRODUCT";
export const CANCEL_PRODUCT = "CANCEL_PRODUCT";
export const UP_PRODUCT = "UP_PRODUCT";
export const DOWN_PRODUCT = "DOWN_PRODUCT";
export const STEP_PRODUCT = "STEP_PRODUCT";

export const SELL = "SELL";
export const SELL_SUCCESS = "SELL_SUCCESS";
export const SELL_FAILD = "SELL_FAILD";

export const BUY = "BUY";
export const BUY_SUCCESS = "BUY_SUCCESS";
